import { Token } from 'types/token';
import { PresetNetworkId } from 'constants/defaultNetwork';

export const DEFAULT_TOKEN_CONFIG: Token[] = [
  {
    symbol: 'ETH',
    decimal: 18,
    name: 'ETH',
    demon: 'wei',
    icon: '',
    chainCustomId: PresetNetworkId.ARBITRUM,
    isNative: true,
    isCustom: false,
    contractAddress: '',
    track: '',
    display: true,
    themeColor: '#000000',
  },
  {
    symbol: 'ETH',
    decimal: 18,
    name: 'ETH',
    demon: 'wei',
    icon: '',
    chainCustomId: PresetNetworkId.ARBITRUM,
    isNative: true,
    isCustom: false,
    contractAddress: '',
    track: '',
    display: true,
    themeColor: '#000000',
  },
  {
    symbol: 'BTC',
    decimal: 18,
    name: 'BTC',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.ARBITRUM,
    isNative: false,
    isCustom: false,
    contractAddress: '0x25f5531AF2a4ba5d474Ad7251c24c1DB1D56C949',
    track: '',
    display: true,
    themeColor: '#FFA800',
  },
  {
    symbol: 'IRIS',
    decimal: 18,
    name: 'IRIS',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.ARBITRUM,
    isNative: false,
    isCustom: false,
    contractAddress: '0x87d41db3a4e0ba30249068aaf64ea6c9899fc6e8',
    track: '',
    display: true,
    themeColor: '#3598db',
  },

  {
    symbol: 'ETH',
    decimal: 18,
    name: 'ETH',
    demon: 'wei',
    icon: '',
    chainCustomId: PresetNetworkId.POLYGON,
    isNative: true,
    isCustom: false,
    contractAddress: '',
    track: '',
    display: true,
    themeColor: '#000000',
  },
  {
    symbol: 'UNI',
    decimal: 18,
    name: 'UNI',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.MAINNET,
    isNative: false,
    isCustom: false,
    contractAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    track: '',
    display: true,
    themeColor: '#3598db',
  },

  {
    symbol: 'BNB',
    decimal: 18,
    name: 'BNB',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.MAINNET,
    isNative: false,
    isCustom: false,
    contractAddress: '0xB8c77482e45F1F44dE1745F52C74426C631bDD52',
    track: '',
    display: true,
    themeColor: '#3598db',
  },
  {
    symbol: 'SHIB',
    decimal: 18,
    name: 'SHIB',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.MAINNET,
    isNative: false,
    isCustom: false,
    contractAddress: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    track: '',
    display: true,
    themeColor: '#3598db',
  },

  {
    symbol: 'OKB',
    decimal: 18,
    name: 'OKB',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.MAINNET,
    isNative: false,
    isCustom: false,
    contractAddress: '0xc715abcd34c8ed9ebbf95990e0c43401fbbc122d',
    track: '',
    display: true,
    themeColor: '#3598db',
  },

  {
    symbol: 'ETH',
    decimal: 18,
    name: 'ETH',
    demon: '',
    icon: '',
    chainCustomId: PresetNetworkId.MAINNET,
    isNative: true,
    isCustom: false,
    contractAddress: '',
    track: '',
    display: true,
    themeColor: '#3598db',
  },
];
